/**
 * Shared types for the AI architecture (Task 25).
 *
 * These types are the common vocabulary every other file in `src/lib/ai/`
 * is built on — `providerInterface.ts` (what a provider must implement),
 * `promptManager.ts` (what it builds), `conversationManager.ts` (what it
 * stores), and `aiService.ts` (what it orchestrates). Deliberately framed
 * generically ("a chat-style provider that takes messages and returns a
 * message") rather than around any one vendor's SDK shape, since no
 * concrete provider is wired up in this task — see `providers/README`
 * note in `README.md` for why.
 */

/** Who authored a given message in a conversation. */
export type ChatRole = "system" | "user" | "assistant";

/** A single message in a conversation, provider-agnostic. */
export interface ChatMessage {
  /** Unique within its conversation. Generated by `ConversationManager`. */
  id: string;
  role: ChatRole;
  content: string;
  /** ISO 8601 timestamp, set by `ConversationManager` when the message is added. */
  createdAt: string;
}

/** Per-request generation tuning, honored on a best-effort basis by each provider. */
export interface GenerateOptions {
  /** 0–1 (or provider-specific range); higher is more random. */
  temperature?: number;
  /** Upper bound on the length of the generated reply. */
  maxTokens?: number;
  /** Strings that should cause the provider to stop generating. */
  stopSequences?: string[];
}

/** Everything a provider needs to produce the next assistant message. */
export interface GenerateRequest {
  /** Full message list in order, typically system prompt(s) + conversation history. */
  messages: ChatMessage[];
  options?: GenerateOptions;
}

/** What a provider hands back after a successful generation. */
export interface GenerateResult {
  /** The new assistant message. Callers append this to the conversation themselves. */
  message: ChatMessage;
  /** Optional token/usage accounting, when a provider reports it. */
  usage?: {
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
  };
  /** The provider's raw, unmodified response — kept for debugging only, never relied upon by callers. */
  raw?: unknown;
}

/**
 * A stable set of machine-readable failure reasons every provider maps its
 * own errors onto, so calling code can react the same way regardless of
 * which vendor is configured (e.g. "show a retry affordance for
 * `rate_limited`", "show a setup hint for `not_configured`").
 */
export type AIErrorCode =
  | "not_configured"
  | "not_implemented"
  | "invalid_request"
  | "authentication_failed"
  | "rate_limited"
  | "provider_error"
  | "network_error"
  | "unknown";

/** A normalized error type every provider throws instead of a vendor-specific error shape. */
export class AIProviderError extends Error {
  readonly code: AIErrorCode;
  readonly cause?: unknown;

  constructor(message: string, code: AIErrorCode, cause?: unknown) {
    super(message);
    this.name = "AIProviderError";
    this.code = code;
    this.cause = cause;
  }
}
